config/routes.rb
Rails.application.routes.draw do

  get 'occurrences' => 'occurrences#index'
  get 'occurrence/new' => 'occurrences#new'
  post 'occurrences' => 'occurrences#create'
  

  root 'occurrences#index'

end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController

  def index
    @occurrences = Occurrence.all
  end

  def new
    @occurrence = Occurrence.new
  end

  def create
    @occurrence = Occurrence.new(occurrence_params)
    if @occurrence.save
      redirect_to occurrences_path
    else
      render 'new'
    end
  end

  private
    def occurrence_params
      params.require(:occurrence).permit(:title, :description, :occurenceType, :address, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acuda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/occurrences/index.html.erb
<h1>Occurrences</h1>
<%= link_to "New occurrence", occurrence_new_path %>
<br/>

<% @occurrences.each do |occurrence| %>
  <div class="occurrence">
    <li>
      <h3><%= occurrence.title %></h3>
      <h5><%= occurrence.description %></h5>
      <p><%= occurrence.occurenceType %></p>
      <p><%= occurrence.address %></p>
      <p><%= occurrence.status %></p>
    </li>
  </div>
<% end %>

app/views/occurrences/new.html.erb
<%= form_for(@occurrence) do |f| %>
  <div class="form">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'  %><br/>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %><br/>

    <%= f.label :occurenceType %>
    <%= f.text_field :occurenceType, class: 'form-control' %><br/>

    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %><br/>

    <%= f.label :status %>
    <%= f.text_field :status, class: 'form-control' %><br/>
  </div>
  <div class="actions">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>